# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    filter_sets:
        small_thumb:
             quality: 75
             filters:
                thumbnail: { size : [320, 230], mode : outbound }
        medium_thumb:
          quality: 75
          filters:
            thumbnail: { size: [600, 430], mode: outbound }
    # valid drivers options include "gd" or "gmagick" or "imagick"
    # driver: "gd"
